LuoBtoC/Controllers/MasterPageController.cs
using SqlModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LuoBtoC.Controllers
{
    public class MasterPageController : Controller
    {
        //
        // GET: /MasterPage/

        public ActionResult Top(SqlModel.MasterPage.TopModels model)
        {
            if (ModelState.IsValid) 
            {
                BLL.Bll_ProductType bllPro = new BLL.Bll_ProductType();
                BLL.bll_InformationType bllInformation=new BLL.bll_InformationType();
                model.ProList = bllPro.GetListByPage(" IsDelete=0 and fid=0", " sort ", 0, 10);
                model.informationList=bllInformation.GetListByPage(" IsDelete=0 and fid=0", " sort ", 0, 10);
            }
            return PartialView(model);
        }

        public ActionResult Left(SqlModel.MasterPage.LeftModels model)
        {
            if (ModelState.IsValid) 
            {
                BLL.Bll_ProductType bllPro = new BLL.Bll_ProductType();
                model.ProList = bllPro.GetListByPage(" IsDelete=0 and fid=0", " sort ", 0, 6);
                BLL.bll_Product bllProduct = new BLL.bll_Product();
                model.ProductList = bllProduct.GetListByPage(" IsDelete=0", " sort", 0, 4);
            }
            return PartialView(model);
        }

        public ActionResult Foot()
        {
            return PartialView();
        }


        
    }
}

LuoBtoC/Views/Shared/BasePage.cshtml
@using SqlModel
@model Collections.BasePageModel
@if (Model != null && Model.TotalPages != 0) 
{
    <ul class="pagination">
        @{
            
            @Url.CreatPageLiTag(Model,Model.CurrentIndex - 1,false, Model.IsHasPrePage, "&laquo;")
            if(Model.TotalPages<=Model.DisplayMaxPages)
            {
                for(int i=1;i<Model.TotalPages;i++)
                {
                    @Url.CreatPageLiTag(Model,i,i==Model.CurrentIndex);
                }
            }
            else
            {
                if(Model.CurrentIndex-1<5)
                {
                    for(int i=1;i<Model.DisplayMaxPages-1;i++)
                    {
                        @Url.CreatPageLiTag(Model,i,i==Model.CurrentIndex);
                    }
                    @Url.CreatPageLiTag(Model,Model.CurrentIndex,false,false,"....");
                }
                else
                {
                    @Url.CreatPageLiTag(Model,1);
                    if(Model.CurrentIndex+(Model.DisplayMaxPages-2)/2>=Model.TotalPages)
                    {
                        int pape=Model.CurrentIndex-(Model.DisplayMaxPages-Model.TotalPages+Model.CurrentIndex-1);
                        if(pape>1)
                        {
                            @Url.CreatPageLiTag(Model,Model.CurrentIndex,false,false,"...");
                        }
                        for(int i=pape+1;i<Model.TotalPages;i++)
                        {
                            @Url.CreatPageLiTag(Model,i,i==Model.CurrentIndex)
                        }
                    }
                    else
                    {
                        int page=Model.CurrentIndex-(Model.DisplayMaxPages-2)/2;
                        if(page>2)
                        {
                            @Url.CreatPageLiTag(Model,Model.CurrentIndex,false,false,"...");
                        }
                        for(int i=page;i<Model.CurrentIndex+(Model.DisplayMaxPages-2)/2;i++)
                        {
                            @Url.CreatPageLiTag(Model,i,i==Model.CurrentIndex);
                        }
                        @Url.CreatPageLiTag(Model,Model.CurrentIndex,false,false,"...");
                    }
                }
            }
            
           @Url.CreatPageLiTag(Model,Model.TotalPages,Model.TotalPages==Model.CurrentIndex);
            @Url.CreatPageLiTag(Model, Model.CurrentIndex + 1, false, Model.IsHasNextPage, "&raquo;")
            
        }
        </ul>
}

LuoBtoC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="zh">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <title>@ViewBag.Title - 我的 ASP.NET MVC 应用程序</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>


    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)

    <center>
        <div id="templatemo_body_wrapper">
            <div id="templatemo_wrapper">
                @Html.Action("Top", "MasterPage")
                <div class="copyrights">Collect from <a href="http://sc.putaojiayuan.com/" title=""></a></div>
                <div id="templatemo_main">
                    @Html.Action("Left", "MasterPage")

                    @RenderBody()
                    <div class="cleaner"></div>

                </div> <!-- END of templatemo_main -->
                @{Html.RenderPartial("~/Views/MasterPage/Foot.cshtml");}
            </div> <!-- END of templatemo_wrapper -->
        </div> <!-- END of templatemo_body_wrapper -->

    </center>
</body>
</html>