LuoBtoC/Controllers/MemberController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SqlSugar;
using System.Data;

namespace LuoBtoC.Controllers
{
    public class MemberController : Controller
    {
        //
        // GET: /Member/

        public ActionResult MemberInfo(SqlModel.MemberModel.Member model)
        {
            if (ModelState.IsValid)
            {
                if (Session["MemberID"] == null)
                {
                    string js = "<script language=javascript>alert('{0}');location.href ='{1}'</script>";
                    Response.Write(string.Format(js, "对不起，您没有登录，或登录时间过长，请重新登录！", "/Account/Login"));
                    Response.End();
                }
                else
                {
                    BLL.bll_Member member = new BLL.bll_Member();
                    model = member.GetModel(SqlSugar.SqlFunc.ToInt64(Session["MemberID"]));
                }
            }

            return View(model);

        }



        public ActionResult Collection(string index, string searchkey)
        {
            if (string.IsNullOrEmpty(index))
            {
                index = "1";
            }
            if (string.IsNullOrEmpty(searchkey))
            {
                searchkey = string.Empty;
            }
            BLL.Bll_Collection bllC = new BLL.Bll_Collection();
            SqlModel.MemberModel.CollectionModel totalList = new SqlModel.MemberModel.CollectionModel();
            string strWhere = "Collection.Isdelete=0 ";
            if (Session["MemberID"] != null)
            {
                strWhere += " and MemberId='" + Session["MemberID"] + "'";
            }
            totalList.CollectionList = bllC.getPape(strWhere, "Id desc");
            Collections.BasePageModel page = new Collections.BasePageModel()
            {
                SearchKeyWord = searchkey,
                CurrentIndex = Int32.Parse(index),
                TotalCount = totalList.CollectionList.Count,
                ActionName = "Collection"
            };
            SqlModel.MemberModel.CollectionModel pageList = new SqlModel.MemberModel.CollectionModel();
            pageList.CollectionList = totalList.CollectionList.Skip((page.CurrentIndex - 1) * page.PageSize).Take(page.PageSize).ToList();
            ViewData["pagemodel"] = page;
            return View(pageList);

        }



        Collections.BuyShopPing bsp = new Collections.BuyShopPing();
        public ActionResult Shoppingcart()
        {
            SqlModel.MemberModel.ShoppingcartModel spm = new SqlModel.MemberModel.ShoppingcartModel();
            if (ModelState.IsValid)
            {

                if (Request.QueryString["mode"] != "view")
                {
                    int pid = Request.QueryString["ProductID"].ObjToInt();
                    int num = Request.QueryString["num"].ObjToInt();
                    if (pid > 0)
                    {
                        BLL.bll_Product proBll = new BLL.bll_Product();
                        SqlModel.Product model = proBll.GetModel(Convert.ToInt64(System.Web.HttpContext.Current.Request["ProductID"]));
                        bsp.UpdateShoppingCart(model);
                    }
                    if (Request.QueryString["flag"] == "Clear")
                    {
                        if (Session["myCartTable"] != null)
                        {
                            DataTable nowTable2 = (DataTable)Session["myCartTable"];
                            nowTable2.Rows.Clear();
                            Session["myCartTable"] = nowTable2;
                        }
                    }
                }
                else
                {
                    if (!string.IsNullOrEmpty(Request.QueryString["Erroinfo"]))
                    {
                        string js = "<script language=javascript>alert('{0}');location.href ='{1}'</script>";
                        Response.Write(string.Format(js, Request.QueryString["Erroinfo"].ToString(), "/Home/index"));
                        Response.End();
                    }
                }



                if (Session["myCartTable"] != null)
                {

                    spm.proModel = Collections.ModelConvertHelper<SqlModel.Product>.ConvertToModel((DataTable)Session["myCartTable"]).ToList();

                }
                ViewBag.litSunMoney = bsp.GetCaculatorSum().ToString("￥0.00");


            }
            return View(spm);
        }

        public ActionResult Review(string index, string searchkey)
        {

            if (string.IsNullOrEmpty(index))
            {
                index = "1";
            }
            if (string.IsNullOrEmpty(searchkey)) 
            {
                searchkey = string.Empty;
            }
            SqlModel.MemberModel.ReviewModel revList = new SqlModel.MemberModel.ReviewModel();
            BLL.bll_Review bllRev = new BLL.bll_Review();
            string whereStr = "Review.Isdelete=0";
            if (Session["MemberID"] != null)
            {
                whereStr += " and MemberId=" + Session["MemberID"].ToString();
            }

            revList.RevieList = bllRev.getPage(whereStr, " Id desc ");
            Collections.BasePageModel page = new Collections.BasePageModel()
            {
                SearchKeyWord = searchkey,
                CurrentIndex = Int32.Parse(index),
                TotalCount = revList.RevieList.Count,
                ActionName = "Review"
            };
            SqlModel.MemberModel.ReviewModel revList2 = new SqlModel.MemberModel.ReviewModel();
            revList2.RevieList = revList.RevieList.Skip((page.CurrentIndex - 1) * page.PageSize).Take(page.PageSize).ToList();
            ViewData["pagemodel"] = page;
            return View(revList2);
        }


        public void lbnTuo()
        {
            Session["MemberID"] = null;
            Session["MemberName"] = null;
            Session["MemberRankId"] = null;
            string js = "<script language=javascript>alert('{0}');location.href ='{1}'</script>";
            Response.Write(string.Format(js, "安全退出成功！", "/Home/index"));
            Response.End();
        }

        public void CollectionDelete(long collectionID)
        {
            BLL.Bll_Collection bllColl = new BLL.Bll_Collection();
            SqlModel.Collection model = bllColl.GetModel(collectionID);
            model.IsDelete = true;
            bllColl.Update(model);
            string js = "<script language=javascript>alert('{0}');location.href ='{1}'</script>";
            Response.Write(string.Format(js, "成功！", "/Member/Collection"));
            Response.End();
        }
    }
}

LuoBtoC/Views/Member/Collection.cshtml
@{
    ViewBag.Title = "Collection";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model SqlModel.MemberModel.CollectionModel

<div id="content" class="float_r">
    <h5 style="text-align:left">会员中心 -》我的收藏</h5>
    <table width="680px" cellspacing="0" cellpadding="5">

        <tr bgcolor="#ddd">
            <th width="90" align="left" nowrap="nowrap" style="border-right:1px #ccc solid;">商品编码 </th>
            <th width="85" align="center" nowrap="nowrap" style="border-right:1px #ccc solid;">商品图片 </th>
            <th align="left" nowrap="nowrap" style="border-right:1px #ccc solid;">商品名称 </th>
            <th width="120" align="left" nowrap="nowrap" style="border-right:1px #ccc solid;">收藏时间 </th>
            <th width="50" align="left" nowrap="nowrap">操作</th>

        </tr>
        @{
            BLL.bll_Product pro = new BLL.bll_Product();
            
            };
        @foreach (var mode in Model.CollectionList)
        {
           
            SqlModel.Product proMode = pro.GetModel(Convert.ToInt64(mode.ProductId));
                             
            <tr>
                <td align="left" style="border-bottom:1px #ccc solid; border-right:1px #ccc solid;">
                    <a href='../Productdetail.aspx?id=@mode.ProductId'>
                       @proMode.ID
                    </a>
                </td>
                <td align="left" style="border-bottom:1px #ccc solid; border-right:1px #ccc solid;">
                    <a href='../Productdetail.aspx?id=@mode.ProductId'>
                        <img src="../Admin/Upfile/ @proMode.ID" alt="@mode.ProductName" title="@mode.ProductName" style="width:80px;" />
                    </a>
                </td>
                <td align="left" style="border-bottom:1px #ccc solid; border-right:1px #ccc solid;">
                    <a href='../Productdetail.aspx?id=@mode.ProductId'>
                        @mode.ProductName
                    </a>
                </td>
                <td align="left" style="border-bottom:1px #ccc solid; border-right:1px #ccc solid;">
                    @DateTime.Parse(@mode.CollectionDate.ToString()).ToString("yyyy-MM-dd hh:mm:ss")
                </td>
                <td align="left" style="border-bottom:1px #ccc solid;">
                    @Html.ActionLink("删除", "CollectionDelete", "Member", new { collectionID = mode.ID }, new { onclick = "return confirm('确认删除？')" })
                </td>
            </tr>
        }


      @Html.Partial("~/Views/Shared/BasePage.cshtml", ViewData["pagemodel"])
    </table>

</div>

LuoBtoC/Views/Member/MemberInfo.cshtml
@{
    ViewBag.Title = "会员基本资料";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model SqlModel.MemberModel.Member
<div id="content" class="float_r">
    <h5 style="text-align:left">会员中心 -》我的基本信息</h5>
    <div class="content_half float_l checkout">
        会员名:
        <p>@Model.MemberName</p>
        <br />
        <br />
        会员等级:
        <p>@Model.MemberRankId</p>
        <br />
        <br />
        邮箱:
        <p>@Model.Email</p>
        <br />
        <br />
        电话:
        <p>@Model.Phone</p>
        <br />
        <br />
        QQ号:
        <p>@Model.QQ</p>
        <br />
        <br />
        地址:
        <p>@Model.Address</p>
        <br />
        <br />
        <a href="javascript:location.href='MemberInfoUpdate.aspx?id=@Model.ID'">
        <img src="../images/btn_Update.jpg"  alt="" height="25px" width="75px" /></a>
    </div>
</div>

LuoBtoC/Views/Member/Review.cshtml
@{
    ViewBag.Title = "Review";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model SqlModel.MemberModel.ReviewModel

<link href="../css/templatemo_style.css" rel="stylesheet" type="text/css" />
<link rel="stylesheet" type="text/css" href="../css/ddsmoothmenu.css" />



<div id="content" class="float_r">
    <h5 style="text-align:left">会员中心 -》我的评论</h5>
    <table width="680px" cellspacing="0" cellpadding="5">
        <tr bgcolor="#ddd">
            <th width="100" align="left" nowrap="nowrap" style="border-right:1px #ccc solid;">商品名称</th>
            <th align="left" nowrap="nowrap" style="border-right:1px #ccc solid;">评论内容</th>
            <th width="120" align="left" nowrap="nowrap" style="border-right:1px #ccc solid;">回复内容</th>
            <th width="120" align="left" nowrap="nowrap" style="border-right:1px #ccc solid;">评论时间</th>
            <th width="50" align="left" nowrap="nowrap">操作</th>

        </tr>
        @foreach (var m in Model.RevieList)
        {
            <tr>
                <td align="left" style="border-bottom:1px #ccc solid; border-right:1px #ccc solid;">
                    @m.ProductName
                </td>
                <td align="left" style="border-bottom:1px #ccc solid; border-right:1px #ccc solid;">
                    @Collections.publicHandle.GetSubstring(m.ReviewContent,16,"...")
                </td>
                <td align="left" style="border-bottom:1px #ccc solid; border-right:1px #ccc solid;">
                    @Collections.publicHandle.GetSubstring(m.ReplyContent, 16, "...")
                </td>
                <td align="left" style="border-bottom:1px #ccc solid; border-right:1px #ccc solid;">
                    @DateTime.Parse(m.ReviewDate.ToString()).ToString("yyyy-MM-dd hh:mm:ss")
                </td>
                <td align="left" style="border-bottom:1px #ccc solid;">
                    @Html.ActionLink("删除", "RevDelete", "Member", new {style="cursor:hand", RevID = m.ID }, new { onclick = "return confirm('您确实要删除吗！')" })
                 </td>
            </tr>
        }
        @Html.Partial("~/Views/Shared/BasePage.cshtml", ViewData["pagemodel"])
    </table>
</div>

LuoBtoC/Views/Member/Shoppingcart.cshtml
@{
    ViewBag.Title = "Shoppingcart";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model SqlModel.MemberModel.ShoppingcartModel

<link href="css/templatemo_style.css" rel="stylesheet" type="text/css" />
<link rel="stylesheet" type="text/css" href="css/ddsmoothmenu.css" />
<script type="text/javascript">
    //我要购买
    function select_adress() {
        var b = window.confirm("您没登录，请先登录？");
        if (b) {
            opendiv('m', 400, 200);
        }

    }
</script>



<div id="content" class="float_r">
    <h3>购物车</h3>
    <table width="680px" cellspacing="0" cellpadding="5">
        <tr bgcolor="#ddd">
            <th width="120" align="left" nowrap="nowrap" style="border-right:1px #ccc solid;">商品图片 </th>
            <th width="180" align="left" nowrap="nowrap" style="border-right:1px #ccc solid;">商品名称 </th>
            <th width="130" align="left" nowrap="nowrap" style="border-right:1px #ccc solid;">商品编码 </th>
            <th width="100" align="left" nowrap="nowrap" style="border-right:1px #ccc solid;">数量 </th>
            <th width="60" align="left" nowrap="nowrap" style="border-right:1px #ccc solid;">单价 </th>
            <th width="60" align="left" nowrap="nowrap" style="border-right:1px #ccc solid;">总金额 </th>
            <th width="90" align="left" nowrap="nowrap" style="border-right:1px #ccc solid;"> 操作</th>

        </tr>
        @if (Model.proModel != null)
        {
            foreach (var m in Model.proModel)
            {
                <tr>
                    <td align="left" style="border-bottom:1px #ccc solid; border-right:1px #ccc solid;">
                        <a href='Productdetail.aspx?id=@m.ID'>
                            <img src='Admin/Upfile/@m.ProductPic' alt="Shoes 1" style="width:100px;" />
                        </a>
                    </td>
                    <td align="left" style="border-bottom:1px #ccc solid; border-right:1px #ccc solid;">
                        @m.ProductName
                    </td>
                    <td align="left" style="border-bottom:1px #ccc solid; border-right:1px #ccc solid;">
                        @m.ProductNo
                    </td>
                    <td align="left" style="border-bottom:1px #ccc solid; border-right:1px #ccc solid;" nowrap="nowrap">
                        <input id="txtProductNum" style="width:20px;text-align:right" title="@Model.proModel.Count" value="@Model.proModel.Count">
                        <input id="LinkButton1" value="修改" style="cursor: hand; padding-top:5px" type="submit">
                    </td>
                    <td align="left" style="border-bottom:1px #ccc solid; border-right:1px #ccc solid;">
                        @Convert.ToDecimal(m.WebsitePrice)
                    </td>
                    <td align="left" style="border-bottom:1px #ccc solid; border-right:1px #ccc solid;">
                        @Convert.ToDecimal(m.ProductTotal)
                    </td>
                    <td align="left" style="border-bottom:1px #ccc solid; border-right:1px #ccc solid;">
                        @Html.ActionLink("删除", "linkbtnDelete", "Member", new { style = "cursor:hand", collectionID = @Model.proModel.Count }, new { onclick = "return confirm('确认删除？')" })
                    </td>
                </tr>
            }
        }


       <tr>

            <td align="left" style="background:#ddd; font-weight:bold" colspan="3">
                商品总金额：@ViewBag.litSunMoney
            </td>

            <td align="right" style="background:#ddd; font-weight:bold" colspan="4">
                <a href="Shoppingcart.aspx?flag=Clear">清空购物车</a>
                &nbsp;
                <a href="Index.aspx">接着去购物</a>
                &nbsp;
                <a href="javascript:history.back()">返回</a>
                &nbsp;
                <input name="btnBuy" value="现在结账" id="btnBuy" style="cursor:hand;" type="submit">
            </td>
        </tr>
    </table>

</div>